### ISSUE TITLE
chaduke - _finalize() fails to check that ``totalCashChange > 0`` when balanceState.storedCashBalance < 0, so it is possible to put an account further into debt when a cash balance is already negative.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#105]
chaduke

medium

# _finalize() fails to check that ``totalCashChange > 0`` when balanceState.storedCashBalance < 0, so it is possible to put an account further into debt when a cash balance is already negative.

## Summary
_finalize() fails to check that ``totalCashChange > 0`` when balanceState.storedCashBalance < 0. As a result, even a cash balance is negative already, it is still possible to  put an account further into debt, which is not allowed as specified in L262. 

## Vulnerability Detail
_finalize()  handles an account's balances, handling any transfer logic required:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/BalanceHandler.sol#L143-L246](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/BalanceHandler.sol#L143-L246)

However, the function fails to check that ``totalCashChange > 0`` when ``balanceState.storedCashBalance < 0``, which means, it is still possible to  put an account further into debt even the account is already negative in ``storedCashBalance``.  This is against the requirement of Notion specified in L262 "If a cash balance is negative already we cannot put an account further into debt."

## Impact
``_finalize()`` fails to check that ``totalCashChange > 0`` when ``balanceState.storedCashBalance < 0``, so it is possible to put an account further into debt when a cash balance is already negative. 

## Tool used
VSCode

Manual Review

## Recommendation
_finalize() needs to check and require ``totalCashChange > 0`` when ``balanceState.storedCashBalance < 0``.

**Comment by jeffywu** [comment]
Invalid, the comment on line 262 only applies to the `setBalanceStorageForfCashLiquidation` function, not the finalize function. If totalCashChange > 0 and storedCashBalance < 0 then the account will be repaying its debt and this is always allowed.
