### ISSUE TITLE
chaduke - localAssetFromLiquidator() might overcalculate ``localAssetFromLiquidator`` and as a result, a liquidator  might pay much more asset cash than he is supposed to (loss of funds)

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#114]
chaduke

high

# localAssetFromLiquidator() might overcalculate ``localAssetFromLiquidator`` and as a result, a liquidator  might pay much more asset cash than he is supposed to (loss of funds)

## Summary
``localAssetFromLiquidator()`` might overcalculate ``localAssetFromLiquidator`` and as a result, a liquidator  might pay much more asset cash than he is supposed to (loss of funds)

## Vulnerability Detail
``localAssetFromLiquidator()``  calculates and returns: 
1) ``collateralBalanceToSell``: the amount of collateral balance to be sold to the liquidator.
2) ``localAssetFromLiquidator``: the amount of asset cash to be paid from the liquidator

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidationHelpers.sol#L174-L207](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidationHelpers.sol#L174-L207)

However, when calculating ``localAssetFromLiquidator``, the function uses ``collateralUnderlyingPresentValue`` instead of the input ``collateralBalanceToSell``, that means, the liquidator needs to pay for the value of the whole collateral underlying present value.

```javascript
 // localPurchased = collateralToSell / (exchangeRate * liquidationDiscount)
        int256 localUnderlyingFromLiquidator =
            collateralUnderlyingPresentValue
                .mul(Constants.PERCENTAGE_DECIMALS)
                .mul(factors.localETHRate.rateDecimals)
                .div(ExchangeRate.exchangeRate(factors.localETHRate, factors.collateralETHRate))
                .div(liquidationDiscount);

        int256 localAssetFromLiquidator =
            factors.localPrimeRate.convertFromUnderlying(localUnderlyingFromLiquidator);
        // localPrimeAvailable must be negative in cross currency liquidations
        int256 maxLocalAsset = factors.localPrimeAvailable.neg();
```

In the worst case (when no future adjustment is made to `` localAssetFromLiquidator ``), the liquidator will pay for the whole amount of the collateral value, but will only receives ``collateralBalanceToSell`` amount of the collateral, a loss of funds scenario. 

## Impact
localAssetFromLiquidator() might overcalculate ``localAssetFromLiquidator`` and as a result, a liquidator  might pay for all the collateral balance value but only receives ``collateralBalanceToSell`` amount of the collateral" (loss of funds)

## Tool used
VScode

Manual Review

## Recommendation
Use  the input ``collateralBalanceToSell`` to calculate ``localAssetFromLiquidator`` instead:

```javascript
 function calculateLocalToPurchase(
        LiquidationFactors memory factors,
        int256 liquidationDiscount,
        int256 collateralUnderlyingPresentValue,
        int256 collateralBalanceToSell
    ) internal pure returns (int256, int256) {
        // Converts collateral present value to the local amount along with the liquidation discount.
        // localPurchased = collateralToSell / (exchangeRate * liquidationDiscount)
        int256 localUnderlyingFromLiquidator =
-            collateralUnderlyingPresentValue
+           collateralBalanceToSell
                .mul(Constants.PERCENTAGE_DECIMALS)
                .mul(factors.localETHRate.rateDecimals)
                .div(ExchangeRate.exchangeRate(factors.localETHRate, factors.collateralETHRate))
                .div(liquidationDiscount);

        int256 localAssetFromLiquidator =
            factors.localPrimeRate.convertFromUnderlying(localUnderlyingFromLiquidator);
        // localPrimeAvailable must be negative in cross currency liquidations
        int256 maxLocalAsset = factors.localPrimeAvailable.neg();

        if (localAssetFromLiquidator > maxLocalAsset) {
            // If the local to purchase will flip the sign of localPrimeAvailable then the calculations
            // for the collateral purchase amounts will be thrown off. The positive portion of localPrimeAvailable
            // has to have a haircut applied. If this haircut reduces the localPrimeAvailable value below
            // the collateralAssetValue then this may actually decrease overall free collateral.
            collateralBalanceToSell = collateralBalanceToSell
                .mul(maxLocalAsset)
                .div(localAssetFromLiquidator);

            localAssetFromLiquidator = maxLocalAsset;
        }

        return (collateralBalanceToSell, localAssetFromLiquidator);
    }
```

**Comment by jeffywu** [comment]
Invalid, fCash notional values (face value at maturity) cannot be directly converted using exchange rates without going through the present value first. The liquidator purchases assets at present value, not face value at maturity.

The collateral balance to sell  i.e. transfer between accounts (face value) is adjusted by the ratio of the maximum local present value that can be liquidated and the local present value of the collateral.
