### ISSUE TITLE
chaduke - depositExactToMintPrimeCash() fails to check ``netTransferExternal == actualTransferExternal``, as a result, the contract might receive not exact, but less amount of underying tokens.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#115]
chaduke

medium

# depositExactToMintPrimeCash() fails to check ``netTransferExternal == actualTransferExternal``, as a result, the contract might receive not exact, but less amount of underying tokens.

## Summary
``depositExactToMintPrimeCash()`` fails to check ``netTransferExternal == actualTransferExternal``, as a result, the contract might receive not exact, but less amount of underlying tokens. This might happen,  for example, when the underlying token is a fee-on-transfer token. 

## Vulnerability Detail
``depositExactToMintPrimeCash()``  allows a user to deposit an exact amount of underlying tokens to mint the specified amount of prime cash.

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/TokenHandler.sol#L148-L166](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/TokenHandler.sol#L148-L166)

However, the function fails to check that ``netTransferExternal == actualTransferExternal``, therefore, it is possible that ``actualTransferExternal < netTransferExternal``. In this case, the amount of underlying tokens that is transferred will be less than required, leading to the contract to lose funds.

``actualTransferExternal < netTransferExternal`` is possible for fees-on-transfer tokens due to the implementation of the ``depositUnderlyingExternal()``:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/TokenHandler.sol#L176-L210](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/TokenHandler.sol#L176-L210)

## Impact
``depositExactToMintPrimeCash()`` fails to check ``netTransferExternal == actualTransferExternal``, as a result, the contract might receive not exact, but less amount of underying tokens. 

## Tool used
VSCode

Manual Review

## Recommendation
Check  ``netTransferExternal == actualTransferExternal``:

```diff
function depositExactToMintPrimeCash(
        address account,
        uint16 currencyId,
        int256 primeCashToMint,
        PrimeRate memory primeRate,
        bool returnNativeTokenWrapped
    ) internal returns (int256 actualTransferExternal) {
        if (primeCashToMint == 0) return 0;
        require(primeCashToMint > 0);
        Token memory underlying = getUnderlyingToken(currencyId);
        int256 netTransferExternal = convertToUnderlyingExternalWithAdjustment(
            underlying, 
            primeRate.convertToUnderlying(primeCashToMint) 
        );

        (actualTransferExternal, /* */) = depositUnderlyingExternal(
            account, currencyId, netTransferExternal, primeRate, returnNativeTokenWrapped
        );

+     require(actualTransferExternal == netTransferExternal);

    }
```

**Comment by jeffywu** [comment]
This points to a real edge case where the `netPrimeSupplyChange != primeCashToMint`, this would be caused by unexpected behavior in the ERC20 token, perhaps caused by fee on transfer tokens.

I'm not sure if the suggested require statement is the right thing to do but some sort of check should be in place here.
