### ISSUE TITLE
PRAISE - router.sol won't be able to re-route calls to some functions in nTokenAction.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#121]
PRAISE

medium

# router.sol won't be able to re-route calls to some functions in nTokenAction.sol

## Summary
the require statements in some functions in nTokenAction.sol will make re-routing calls in the router.sol to it via the fallback() function fail. 

## Vulnerability Detail
some functions in nTokenAction.sol has this require statement which is implemented as Access control
```solidity
        require(msg.sender == nTokenAddress);
```
and 
```solidity
        require(msg.sender == pCashAddress);
```

Now the above require statement will make any call to this functions that isn't from the nTokenAddress or pCashAddress to fail.

And fallback() function in router.sol makes a call to these functions here:
```solidity
    fallback() external payable {
        _delegate(getRouterImplementation(msg.sig));
    }
```

and the fallback function uses `getRouterImplementation()` function to return the implementation contract for the method signature to call, and the following functions are among the sig:

nTokenTransferApprove
```solidity
            sig == nTokenERC20.nTokenTransferApprove.selector 
```

 pCashTransferApprove
```solidity
            sig == nTokenERC20.pCashTransferApprove.selector 
```

nTokenTransfer
```solidity
            sig == nTokenERC20.nTokenTransfer.selector 
```

pCashTransfer
```solidity
            sig == nTokenERC20.pCashTransfer.selector 
```

nTokenTransferFrom
```solidity
            sig == nTokenERC20.nTokenTransferFrom.selector
```

PCashTransferFrom
```solidity
            sig == nTokenERC20.pCashTransferFrom.selector
```
So re-routing calls to these functions via the fallback functions will fail as the require statement will fail.

## Impact
So re-routing calls to these functions via the fallback functions will fail as the require statement will fail.

## Code Snippet
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L295-L297

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L161

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenAction.sol#L110

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L167

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenAction.sol#L124

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L162

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenAction.sol#L144

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L168

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenAction.sol#L158

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L163

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenAction.sol#L181

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenAction.sol#L211

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L169

## Tool used

Manual Review

## Recommendation
To interact with these functions from the router.sol contract, you would need to use a different approach. One possible solution is to have a separate function in the nToken contract that allows the router.sol contract to approve transfers on behalf of the nToken and pCash contracts. This separate function could include additional access control checks to ensure that only authorized contracts, such as the router.sol contract, can call it.

**Comment by Love4codes** [comment]
"I mean it's true that this function will fail to execute when called via Router.sol if it is simply from a user, however, there isn't any actual issue caused by this. nTokenERC20Proxy.sol is meant to proxy these calls to Notional and will therefore satisfy the require(msg.sender == nTokenAddress) check. The same applies to PrimeCashProxy.sol."

**that's not the issue bro..**

**rerouting calls to these functions via router.sol will fail because of those access control checks**

**Comment by Love4codes** [comment]
Yes but that's not the issue I reported, please try to read my report.

"_They are meant to be safeguarded and only callable by nTokenERC20Proxy.sol_"

Yes but router.sol makes calls to these functions that are safeguarded and only callable by nTokenERC20Proxy.sol in a bid to reroute calls to them.
This will fail because the require statements will fail that's the issue here.

**Comment by Trumpero** [comment]
I believe the warden was misled regarding the behavior of `delegatecall`. The `delegatecall` of the router does not alter `msg.sender` and will satisfy the check as mentioned in the comments by Leastwood. Therefore, this issue should be considered invalid.
https://docs.soliditylang.org/en/v0.8.6/introduction-to-smart-contracts.html?highlight=delegatecall#delegatecall-callcode-and-libraries

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non-issue based on the comments above
