### ISSUE TITLE
chaduke - LiquidateCurrencyAction#liquidateLocalCurrency() will always fail when haircut = 0 or buffer = 0 due to divide-by-zero revert in LiquidationHelpers.calculateLocalLiquidationUnderlyingRequired.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#125]
chaduke

medium

# LiquidateCurrencyAction#liquidateLocalCurrency() will always fail when haircut = 0 or buffer = 0 due to divide-by-zero revert in LiquidationHelpers.calculateLocalLiquidationUnderlyingRequired.

## Summary

``LiquidateCurrencyAction#liquidateLocalCurrency()`` will always fail when haircut = 0 or buffer = 0 due to divide-by-zero revert in ``LiquidationHelpers.calculateLocalLiquidationUnderlyingRequired.``

## Vulnerability Detail

To see this, consider the flow: 
``LiquidateCurrencyAction#liquidateLocalCurrency()
-> _localCurrencyLiquidation()
-> LiquidateCurrency.liquidateLocalCurrency()
-> LiquidationHelpers.calculateLocalLiquidationUnderlyingRequired``, 

``LiquidationHelpers.calculateLocalLiquidationUnderlyingRequired()`` aims to 
Calculates the amount of underlying benefit required for local currency liquidation:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidationHelpers.sol#L125-L146](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidationHelpers.sol#L125-L146)

However, this function will always revert due to the division-by-zero error below when ``haircut = 0`` or ``buffer = 0``, which implies ``multiple = 0``. 

```javascript
return localETHRate.convertETHTo(netETHValue.neg())
                    .mul(Constants.PERCENTAGE_DECIMALS)
                    .div(multiple);
```

In summary, if the community votes for ``haircut = 0`` or ``buffer = 0`` for a particular currency, then ``LiquidateCurrencyAction#liquidateLocalCurrency()`` might break due to such a division-by-zero error.

## Impact
LiquidateCurrencyAction#liquidateLocalCurrency() will always fail when haircut = 0 or buffer = 0 due to divide-by-zero revert in LiquidationHelpers.calculateLocalLiquidationUnderlyingRequired.

## Tool used
VSCode

Manual Review

## Recommendation
Consider the edge case of ``haircut = 0`` or ``buffer = 0`` appropriately.

**Comment by jeffywu** [comment]
Invalid, a require statement exists in this function to prevent divide by zero errors.
