### ISSUE TITLE
chaduke - ``LiquidateCurrencyAction#liquidateCollateralCurrency()  will revert or lead the contract to loss funds when ``localBuffer / liquidationDiscount) <= collateralHaircut``.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#129]
chaduke

high

# ``LiquidateCurrencyAction#liquidateCollateralCurrency()  will revert or lead the contract to loss funds when ``localBuffer / liquidationDiscount) <= collateralHaircut``.

## Summary
``LiquidateCurrencyAction#liquidateCollateralCurrency()  will revert or lead the contract to loss funds when ``localBuffer / liquidationDiscount) <= collateralHaircut``.

## Vulnerability Detail

Consider the flow ``LiquidateCurrencyAction#liquidateCollateralCurrency() -> _collateralCurrencyLiquidation -> LiquidateCurrency.liquidateCollateralCurrency() -> _calculateCollateralToRaise()``.  Pay attention to the implementation of  ``_calculateCollateralToRaise()``:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidateCurrency.sol#L206-L258](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidateCurrency.sol#L206-L258)

When ``localBuffer / liquidationDiscount) == collateralHaircut``, L251 will have a divide-by-zero error, the function and thus, the whole flow, as well as ``LiquidateCurrencyAction#liquidateCollateralCurrency()`` will revert in this case. 

When ``localBuffer / liquidationDiscount) < collateralHaircut``, the denominator will be negative, as a result, both ``requiredCollateralPrimeCash`` and ``localPrimeCashFromLiquidator`` will be negative, in contrast to the expectation that they should be both positive.  As a result,  instead of paying prime cash from the liquidator, the contract will pay the liquidator with prime cash. So the function will not work properly in this case. Loss of funds for the contract. 

## Impact
``LiquidateCurrencyAction#liquidateCollateralCurrency()  will revert or lead the contract to loss funds when ``localBuffer / liquidationDiscount) <= collateralHaircut``.

## Tool used
VScode

Manual Review

## Recommendation
Add a require statement to make sure ``localBuffer / liquidationDiscount) > collateralHaircut``.

**Comment by jeffywu** [comment]
```
localBuffer >= 100
liquidationDiscount >= 100
collateralHaircut <= 100
```

Since we choose the max liquidation discount between two currencies, it is technically possible to end up with a negative value in the denominator here. Example:

`denominator = 101 * 100 / 106 - 99 = -3`

It's not immediately clear what the consequences of this are but this would definitely be unexpected. This would require poor parameter setting by governance but that may happen by mistake. A require statement would be wise here.
