### ISSUE TITLE
chaduke - LiquidationHelpers#calculateLocalToPurchase() applies liquidation discount as division instead of multiplication, leading to wrong localAssetFromLiquidator calculation and more payment from the liquidator instead.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#139]
chaduke

high

# LiquidationHelpers#calculateLocalToPurchase() applies liquidation discount as division instead of multiplication, leading to wrong localAssetFromLiquidator calculation and more payment from the liquidator instead.

## Summary
``LiquidationHelpers#calculateLocalToPurchase()`` applies liquidation discount as division instead of multiplication, leading to wrong localAssetFromLiquidator calculation and more payment from the liquidator instead (loss of funds for the liquidator).

## Vulnerability Detail

``LiquidationHelpers#calculateLocalToPurchase()``  calculates the amount of local prime cash that a liquidator needs to pay for purchasing discounted collateral. 

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidationHelpers.sol#L174-L207](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidationHelpers.sol#L174-L207)

The liquidator can pay less than the face value of the collateral  enjoying the discount ``liquidationDiscount``. 

However, the following code shows that  ``liquidationDiscount`` is applied with division instead of multiplication. As a result, the liquidator actually needs to pay more than the face value of the collateral, leading to loss of funds. The correct formula should be

``localPurchased = collateralToSell * liquidationDiscount) / (exchangeRate``

```javascript
int256 localUnderlyingFromLiquidator =
            collateralUnderlyingPresentValue
                .mul(Constants.PERCENTAGE_DECIMALS)
                .mul(factors.localETHRate.rateDecimals)
                .div(ExchangeRate.exchangeRate(factors.localETHRate, factors.collateralETHRate))
                .div(liquidationDiscount);
```

## Impact
LiquidationHelpers#calculateLocalToPurchase() applies liquidation discount as division instead of multiplication, leading to wrong localAssetFromLiquidator calculation and more payment from the liquidator instead.

## Tool used
VSCode

Manual Review

## Recommendation
Apply the discount with multiplication instead of division and make adjustment of ratio decimals appropriately.

**Comment by jeffywu** [comment]
Invalid, this calculation is correct based on the direction of the exchange rate.
