### ISSUE TITLE
chaduke - LiquidateCurrencyAction#liquidateCollateralCurrency() allows the liquidator to enjoy liquidation discount TWICE for purchasing nTokens, as a result, the liquidated account loses funds.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#141]
chaduke

high

# LiquidateCurrencyAction#liquidateCollateralCurrency() allows the liquidator to enjoy liquidation discount TWICE for purchasing nTokens, as a result, the liquidated account loses funds.

## Summary
``LiquidateCurrencyAction#liquidateCollateralCurrency()`` allows the liquidator to enjoy liquidation discount TWICE for purchasing nTokens, as a result,  the liquidated account lose more funds. When the function calculates (requiredCollateralPrimeCash, localPrimeCashFromLiquidator). The liquidation discount has already been applied. However, when ``_calculateCollateralNTokenTransfer()`` is called to calculate the amount of NTokens to be sent to the liquidator, the discount is applied again. As a result, the liquidator enjoys double liquidation discount.  

The following analysis will more clear if we assume ``balanceState.storedCashBalance = 0`` so that we can focus our analysis only on ntokens.

## Vulnerability Detail
``LiquidateCurrencyAction#liquidateCollateralCurrency()`` allows a liquidator to purchase cash, ntokens in the collateral currency  (such as cUSDC) with discount to liquidate a local currency debt (such as cDAI)

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/LiquidateCurrencyAction.sol#L182-L254](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/LiquidateCurrencyAction.sol#L182-L254)

However, the function allows a liquidator to enjoy liquidation discount twice for ntokens (not for collateral cash though), consider the LiquidatteCurrency#liquidateCollateralCurrency():

1. calculate collateral prime cash to raise and the local prime cash a liquidator needs to pay. ``(requiredCollateralPrimeCash, localPrimeCashFromLiquidator)``.  At this point, the liquidation discount has already been applied. In other words, the contract just needs to send ``requiredCollateralPrimeCash`` value of collateral cash, ntokens to the liquidator, at the same time, the liquidator sends ``localPrimeCashFromLiquidator`` of local prime cash to the liquidated account, then it is an even deal. The liquidator will enjoy the liquidation discount as profit: pay less than what he gets. 

2. First in liquidation preference is the cash balance. Take as much cash as allowed. The code is correct, no liquidation discount is applied again here. It is 1-1 sent from the liquidated account to the liquidator. 

3. Second, it will calculate the amount nTokens to be transferred to the liquidator. Unfortunately, liquidation discount is applied again. The prime cash value of the ntokens  is discounted here, leading to the contract to send more than ``requiredCollateralPrimeCash`` to the liquidator!

4. Finally, any remaining needed collateral prime cash is debited from the collateral cash balance as a debt. Again, there is no application of liquidation discount again here. The code is correct for this case. 

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidateCurrency.sol#L151-L202](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidateCurrency.sol#L151-L202)

The following code for ``_calculateCollateralNTokenTransfer()`` shows that the liquidation discount is applied again, and the contract will send to the liquidator collateral assets that are worth  more than ``requiredCollateralPrimeCash``, which is calculated in step 1. This is because when calculating ``collateralPrimeRemaining``, the prime cash value of the selling ntokens is discounted (which should not be).

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidateCurrency.sol#L275C5-L325](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/liquidation/LiquidateCurrency.sol#L275C5-L325)

## Impact
LiquidateCurrencyAction#liquidateCollateralCurrency() allows the liquidator to enjoy liquidation discount TWICE for purchasing nTokens, as a result, the liquidated account lose more funds. 

## Tool used
VSCode

Manual Review

## Recommendation
``_calculateCollateralNTokenTransfer()`` should not apply liquidation discount again, one should send ntokens to the liquidator at the face value.

**Comment by jeffywu** [comment]
The second haircut for nTokens is by design. nTokens have their own risk factors similar to fCash. Liquidation of nTokens and fCash mean two sets of discounts being applied. A liquidation discount for cross currency and a liquidation discount specific to the nToken or fCash asset.

I would not consider this valid, this is by design.
