### ISSUE TITLE
PRAISE - There can be excess ETH in depositUnderlyingToken() function and users won't be able to choose if they want the excess ETH returned as WETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#148]
PRAISE

medium

# There can be excess ETH in depositUnderlyingToken() function and users won't be able to choose if they want the excess ETH returned as WETH

## Summary
The depositUnderlyingToken() function in AccountAction.sol can receive excess ETH

## Vulnerability Detail
1. The depositUnderlyingToken() function fails to check that msg.value is strictly equal to `amountExternalPrecision` with a check like this
```solidity
require(amountExternalPrecision == msg.value, "must correspond!")
```
Now the msg.value can be a completely different value from `amountExternalPrecision`

2. because the function assumes that there won't be excess ETH without enforcing it with a require statement, the function fails to give users the opportuinity to withdraw the excess ETH as WETH.
It is missing this bool
```solidity
 bool returnExcessWrapped
```
## Impact
1. the AccountAction.sol's depositUnderlyingToken() function can receive Excess ETH
2. Users aren't given the opportuinity to withdraw excess ETH as WETH

## Code Snippet
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/AccountAction.sol#L84

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/BalanceHandler.sol#LL91C8-L91C33
## Tool used

Manual Review

## Recommendation
1. if AccountAction.sol's depositUnderlyingToken() function isn't meant to receive excess ETH pls enforce it by adding this check. (first convert the amountExternalPrecision to a normal value and then use it in the require statement)

```solidity
require(convertedAmountExternalPrecision == msg.value, `must correspond!`)
```

3. or give users the opportuinity to withdraw the excess ETH as WETH by adding this bool
```solidity
 bool returnExcessWrapped
```

**Comment by Love4codes** [comment]
Ecalate for 10 USDC

This should be valid because
1. the depositUnderlyingToken() function in AccountAction.sol is payable
2.  there's no check to ensure `msg.value` is == `amountExternalPrecision`

**Comment by Trumpero** [comment]
Disagree with the escalation. This issue should be invalid because of 2 reasons:
1. The excess ETH is already returned to the sender in [`TokenHandler.depositUnderlyingExternal()`](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/TokenHandler.sol#L189-L193). Therefore, checking `msg.value` is unnecessary.
2. Any issue related to incorrect `msg.value` can be considered as a user input issue and not a valid medium.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is user input validation to make sure the correct eth is sent, considering this a low issue.
