### ISSUE TITLE
chaduke - Rounding errors in the calculation of liquidity tokens to remove from each market leads to the loss of funds for the redeemer. In the worst case, a redeemer might not be able to claim anything from a market with a small liquidity.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#149]
chaduke

high

# Rounding errors in the calculation of liquidity tokens to remove from each market leads to the loss of funds for the redeemer. In the worst case, a redeemer might not be able to claim anything from a market with a small liquidity.

## Summary
Rounding errors in the calculation of liquidity tokens in ``nTokenCalculations.getLiquidityTokenWithdraw()`` to remove from each market leads to the loss of funds for the redeemer. In the worst case, a redeemer might not be able to claim anything from a market with a small liquidity. 

The main problem is that amount of liquidity tokens that will be removed from each market is in proportion to the ``tokensToRedeem``, with  rounding down error for each market, in particular for small markets, the redeemed total value will be less than what the redeemer deserve. 

## Vulnerability Detail
The redeem function allows a user to redeems nTokens for asset cash and fCash:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenRedeemAction.sol#L70-L81](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/nTokenRedeemAction.sol#L70-L81)

The amount of liquidity tokens that need to be removed for each market is calculated by the ``nTokenCalculations#getLiquidityTokenWithdraw()`` function and returned in array tokensToWithdraw[].

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/nToken/nTokenCalculations.sol#L120-L186](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/nToken/nTokenCalculations.sol#L120-L186)

The problem is that when calculating the liquidity tokens for each market, the formula used is: ``redeemerShare = totalTokens * nTokensToRedeem / totalSupply`` (assume ``ifCashBits= 0``), with the following code: 

```javascript
 tokensToWithdraw[i] = totalTokens
                .mul(nTokensToRedeem)
                .mul(totalPortfolioAssetValue);

            tokensToWithdraw[i] = tokensToWithdraw[i]
                .div(totalPrimeValueInMarkets)
                .div(nToken.totalSupply);
```
Assume `ifCashBits= 0``, which means we do not have idiosyncratic markets, then ``totalPortfolioAssetValue = totalPrimeValueInMarkets``. The case for   ``ifCashBits != 0`` can be analyzed similarly.  The problem is that we will have round down error for each market, especially for small markets (with smaller liquidity tokens).

Consider three markets:  ``totalTokens[1] = 999``, ``totalsTokens[2] = 999``, ``totalsTokens[3] = 200,000``, ``totalSupply = 1,000,000``, ``nTokensToRedeem = 1000``, then we have ``tokensToWithdraw[1] = 0``, ``tokensToWithdraw[2] = 0``, and ``tokensToWithdraw[3] = 200``.

As a result, nothing will be withdrawn from market 1 and market 2 due to the rounding down error. Such loss should be compensated in terms of prime cash in the last step to the redeemer. However, such correction has not been done in the implementation of redeem(). 

In summary, redeem() should consider the rounding errors in each market, which could be significant since liquidity tokens are the share of the total value of the market, and one liquidity token might represent a significant amount of market value share. A final step in redeem() is necessary to compensate for such loss in the calculation of liquidity tokens in each market. In this way, what the redeemer gets will be indeed be:  ``totalPortfolioAssetValue*nTokensToRedeem/supply`` but not less (the rounding error here will be ignorable).

## Impact
Rounding errors in the calculation of liquidity tokens to remove from each market leads to the loss of funds for the redeemer. In the worst case, a redeemer might not be able to claim anything from a market with a small liquidity. 

## Tool used
VSCode

Manual Review

## Recommendation
Calculate the value of all the removed liquidity tokens in ``totalValueForRemovedLiquidityTokens``, and the  redeem goal: ``redeeemValue = totalPortfolioAssetValue*nTokensToRedeem/supply`` and then compensate the redeemer with ``(redeeemValue - `totalValueForRemovedLiquidityTokens)`` in prime cash in the final step.

**Comment by jeffywu** [comment]
I would not consider this a valid issue, rounding errors should go in favor the protocol not the redeemer. In low liquidity markets, there would not be much value to redeem in any case.
