### ISSUE TITLE
chaduke - nTokenCalculations#getNTokenMarketValue() will always revert when some markets have not been initialized, as a result, nTokenMintAcdtion#nTokenMint() will fail as well in this case.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#161]
chaduke

medium

# nTokenCalculations#getNTokenMarketValue() will always revert when some markets have not been initialized, as a result, nTokenMintAcdtion#nTokenMint() will fail as well in this case.

## Summary
``nTokenCalculations#getNTokenMarketValue()`` will always revert when some markets have not been initialized, as a result, ``nTokenMintAcdtion#nTokenMint()`` will fail as well in this case. 

## Vulnerability Detail
``nTokenCalculations#getNTokenMarketValue()`` will evaluate the value of a NToken across all markets. This function is called by ``nTokenMintAcdtion#nTokenMint()``  to decide how much nTokens should be minted. 

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/nToken/nTokenCalculations.sol#L194-L241](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/nToken/nTokenCalculations.sol#L194-L241)

at L121, the function calls ``AssetHandler.getCashClaims()`` to determine the amount of prime cash and fcash claim for each market: 

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/valuation/AssetHandler.sol#L120-L129](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/valuation/AssetHandler.sol#L120-L129)

L127-128 will have a divide-by-zero error when market.totalLiquidity = 0. This happens when a market has not been initialized, for example,  when cash groups extend maxMarketIndex before initializing. In this case, the function should return (0, 0) but it reverts instead. 

As a result, when one of the markets has not been initialized, then ``AssetHandler.getCashClaims()`` will revert, so will ``nTokenCalculations#getNTokenMarketValue()`` and ``nTokenMintAcdtion#nTokenMint()``. 

## Impact
``nTokenCalculations#getNTokenMarketValue()`` will always revert when some markets have not been initialized, as a result, ``nTokenMintAcdtion#nTokenMint()`` will fail as well in this case. 

## Code Snippet
VScode

## Tool used

Manual Review
Return (0, 0) when a market has not been initialized for ``AssetHandler.getCashClaims()``:

```diff
function getCashClaims(PortfolioAsset memory token, MarketParameters memory market)
        internal
        pure
        returns (int256 primeCash, int256 fCash)
    {
        require(isLiquidityToken(token.assetType) && token.notional >= 0); // dev: invalid asset, get cash claims

+    if(market.totalLiquidity == 0) return (0, 0);

        primeCash = market.totalPrimeCash.mul(token.notional).div(market.totalLiquidity);
        fCash = market.totalfCash.mul(token.notional).div(market.totalLiquidity);
    }
```

**Comment by jeffywu** [comment]
Invalid, returning a zero value here will cause accounts to get liquidated.
