### ISSUE TITLE
xiaoming90 - Sequencer offline potentially leaving bad debt or account unfairly liquidated

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#182]
xiaoming90

medium

# Sequencer offline potentially leaving bad debt or account unfairly liquidated

## Summary

If the sequencer goes offline, it might be possible that accounts would be undercollateralized leaving bad debt to the protocol or accounts would be unfairly liquidated.

## Vulnerability Detail

When a sequencer goes offline, users can still continue to "interact" with the protocol by submitting a transaction for L2 directly through Arbitrum's delayed inbox on Ethereum. Note these transactions in Arbitrum's delay inbox will not be executed yet until the sequencer comes online later. 

Once the sequencer returns online, all transactions of the delayed inbox are executed before any others. In other words, the sequencer processes all transactions from the delayed inbox before it accepts new transactions.

Due to time constraints and the limited resources available regarding the implementation of the Chainlink protocol, it is unsure how Chainlink would deal with price updates to L2's price aggregator contract when the sequencer is offline. The following are two possible actions:

- Scenario 1 - Continue submitting the price update, but it should be rejected or dropped until the sequencer come online again; OR

- Scenario 2 - Submit the price update via Arbitrum's delay inbox (Unlikely)

Regardless of the actual action Chainlink took, there will be some form of the issue anyway. Let's consider both scenarios for completeness.

**Scenario 1**

Assume the first scenario and XYZ token is a collateral accepted by Notional. 

1) Before the sequencer went down, the price of XYZ token was worth 100 USD. Bob holds some collateral denominated in XYZ in his Notional account. Bob holds 3 XYZ tokens. Thus, the value of his collateral value is 300 USD (ignoring any sort of haircut for simplicity).
2) When the sequencer went down, the market price of XYZ tokens dropped significantly to 1 USD.
3) At this point, note that the price of the XYZ token on Arbitrum is still 100 USD because no price update can be performed since the sequencer is down.
4) Bob knows that the collateral value of his Notional account on Arbitrum would surely become worthless (3 USD) when the price update propagates to Arbitrum (L2) once the sequencer goes online. He decided to "front-run" the price update by sending a transaction to Arbitum's delay inbox to borrow as many assets as possible and forward them to his wallet address while the value of his collateral was still worth 300 USD.
5) When the sequencer goes online, it will first take Bob's transactions from the delay inbox and execute them on L2. Note that TXs in delay inbox are executed before any others.
6) After some time, the Chainlink price update TX gets executed by the sequencer, and the collateral value of Bob's Notional account will be updated to 3 USD. However, Bob has already borrowed around 300 USD worth of assets from Notional. Thus, making his account seriously undercollateralized, leaving bad debt to the protocol.

**Scenario 2**

Assume the second scenario and XYZ token is a collateral accepted by Notional.

1) Before the sequencer went down, the price of XYZ token was worth 100 USD.
2) When the sequencer went down, the market price of XYZ tokens dropped significantly to 1 USD. Assume that the price update is sent to Arbitrum's delay inbox directly.
3) The liquidators (with their bots) notice that there will be a mass liquidation on many of the Notional accounts collateralized by XYZ in Arbitrum (L2). They take advantage of the situation and submit the liquidation transactions directly to the Arbitum's delay inbox.
4) In theory, some borrowers can still avoid liquidation by closing their position through this delayed inbox (if they are faster than liquidation bots). However, it is unlikely that normal borrowers would have the required knowledge to do so or have a faster reaction than bots.
5) Once the sequencer goes online, all the Notional accounts collateralized by XYZ token instantly get liquidated when the liquidator's transactions in the delay inbox get executed on L2.
6) Before the borrowers have any chance to "top-up" or re-collateralize their accounts, their accounts have been liquidated and their collaterals sold off at below-market value.

If the sequencer is offline for a long period and Bob's transactions are in the delayed inbox for a sufficient amount of time (around 24 hours), he could perform a [Force Inclusion](https://developer.arbitrum.io/sequencer#unhappyuncommon-case-sequencer-isnt-doing-its-job) to move them from the delayed inbox into the core inbox, at which point it’s finalized. In this case, he does not have to wait for the sequencer to be back online for his transactions to be executed on L2.

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/adapters/ChainlinkAdapter.sol#L45

```solidity
File: ChainlinkAdapter.sol
38:         int256 baseToUSD;
39:         (
40:             roundId,
41:             baseToUSD,
42:             startedAt,
43:             updatedAt,
44:             answeredInRound
45:         ) = baseToUSDOracle.latestRoundData();
46:         require(baseToUSD > 0, "Chainlink Rate Error");
47:         (
48:             /* roundId */,
49:             int256 quoteToUSD,
50:             /* uint256 startedAt */,
51:             /* updatedAt */,
52:             /* answeredInRound */
53:         ) = quoteToUSDOracle.latestRoundData();
54:         require(quoteToUSD > 0, "Chainlink Rate Error");
```

## Impact

Scenario 1 - Accounts would be undercollateralized, leaving bad debt to the protocol

Scenario 2 - Accounts would have been unfairly liquidated and their collaterals sold off at below-market value before the borrowers have any chance to "top-up" or re-collateralize their accounts

## Code Snippet

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/adapters/ChainlinkAdapter.sol#L45

## Tool used

Manual Review

## Recommendation

This is a well-known operational issue for protocol running on L2. It is recommended to implement some measures (e.g., a grace period) to mitigate such a risk when the sequencer is offline.

Chainlink has the L2 Sequencer Uptime Feeds (https://docs.chain.link/data-feeds/l2-sequencer-feeds) to allow protocols running on L2 to check sequencer availability and manage the risk.

AAVE V3 ([Aave’s Price Sentinel Contract](https://github.com/aave/aave-v3-core/blob/master/contracts/protocol/configuration/PriceOracleSentinel.sol)) manages this risk by introducing a grace period that disallows liquidation and borrowing after the sequencer goes online for a period of time. Refer to AAVE V3's technical whitepaper for more details (https://github.com/aave/aave-v3-core/blob/master/techpaper/Aave_V3_Technical_Paper.pdf).

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC.

the chainlink oracle and sequencer is not in scope, so the issue should not be a seperate medium

and the code is clearly not compatible with L2 and the code is only ready for migration on mainet

**Comment by 0xleastwood** [comment]
> Escalate for 10 USDC.
> 
> the chainlink oracle and sequencer is not in scope, so the issue should not be a seperate medium
> 
> and the code is clearly not compatible with L2 and the code is only ready for migration on mainet

No, the Notional team has stated that they would consider issues around chainlink oracle staleness if it were to function differently in an L2 environment. Arbitrum and Optimism are two L2s which are being actively considered by the team.

**Comment by 0xleastwood** [comment]
> > > Escalate for 10 USDC.
> > > the chainlink oracle and sequencer is not in scope, so the issue should not be a seperate medium
> > > and the code is clearly not compatible with L2 and the code is only ready for migration on mainet
> > 
> > 
> > No, the Notional team has stated that they would consider issues around chainlink oracle staleness if it were to function differently in an L2 environment. Arbitrum and Optimism are two L2s which are being actively considered by the team.
> 
> Is it via private messaging? The oracle is not in scope in the scope of the onchain readme sir, the code is just not build for L2 network in this version

Yes, we had a discord channel set up with the team where we discussed many of our issues during the contest.

**Comment by Jiaren-tang** [comment]
> > > > Escalate for 10 USDC.
> > > > the chainlink oracle and sequencer is not in scope, so the issue should not be a seperate medium
> > > > and the code is clearly not compatible with L2 and the code is only ready for migration on mainet
> > > 
> > > 
> > > No, the Notional team has stated that they would consider issues around chainlink oracle staleness if it were to function differently in an L2 environment. Arbitrum and Optimism are two L2s which are being actively considered by the team.
> > 
> > 
> > Is it via private messaging? The oracle is not in scope in the scope of the onchain readme sir, the code is just not build for L2 network in this version
> 
> Yes, we had a discord channel set up with the team where we discussed many of our issues during the contest.

Well that equals to DM sponsor, which is a purely valid approach, I have no further comments, unlikely to change payout anyway 👍

**Comment by Trumpero** [comment]
Agree with Senior Watson Leastwood, this should be a valid issue.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Given that this is out of scope the issue from the contest perspective. And discussions in discord cannot be considered over readme.
Considering this a low
