### ISSUE TITLE
xiaoming90 - Prime vaults do not consider secondary debt when assessing vault fees

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#186]
xiaoming90

high

# Prime vaults do not consider secondary debt when assessing vault fees

## Summary

Prime vaults do not have a maturity and are therefore charged fees on a pro-rata basis. However, when prime fees are assessed, only primary debt is taken into consideration and hence vaults much make use of multiple currencies will charge vault accounts according to the composition of their debt. Furthermore, it's important to note that vault account liquidations allow for debt compositions to change depending on what currencies are liquidated.

## Vulnerability Detail

Vault fees are assessed in _two_ different ways:
 - Assessed based on the length of time funds are borrowed. This scales linearly based on the maturity date and is only applicable to non-prime vault positions.
 - Prime vaults calculate fees at a fixed yearly rate and accrue these fees in key parts of the codebase.

As the vault implementation has been modified to accommodate secondary borrow currencies, it doesn't seem fair that fee assessment would be applied to vault users differently. It's incorrect to assume that all users hold the same proportion of debt in each borrowed currency. 

Users can also self-liquidate their primary debt to zero and avoid paying vault fees altogether.

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultAccount.sol#L475-L480

```solidity
File: VaultAccount.sol
405:     function settleVaultAccount(
406:         VaultAccount memory vaultAccount,
407:         VaultConfig memory vaultConfig
408:     ) internal returns (bool didSettle, bool didTransfer) {
             ...
468: 
469:         // Assess prime cash vault fees into the temp cash balance. The account has accrued prime cash
470:         // fees on the time since the fCash matured to the current block time. Setting lastUpdateBlockTime
471:         // to the fCash maturity, will calculate the fees accrued since that time.
472:         vaultAccount.lastUpdateBlockTime = vaultAccount.maturity;
473:         vaultAccount.maturity = Constants.PRIME_CASH_VAULT_MATURITY;
474:         vaultAccount.accountDebtUnderlying = vaultConfig.primeRate.convertDebtStorageToUnderlying(accountPrimeStorageValue);
475:         vaultConfig.assessVaultFees(
476:             vaultAccount,
477:             vaultConfig.primeRate.convertFromUnderlying(vaultAccount.accountDebtUnderlying).neg(),
478:             Constants.PRIME_CASH_VAULT_MATURITY,
479:             block.timestamp
480:         );
```

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultAccount.sol#L487-L506

```solidity
File: VaultAccount.sol
487:     function settleAccountOrAccruePrimeCashFees(
488:         VaultAccount memory vaultAccount,
489:         VaultConfig memory vaultConfig
490:     ) internal returns (bool didSettle) {
491:         // If the vault has matured, it will exit this settlement call in the prime cash maturity with
492:         // fees assessed up to the current time. Transfers may occur but they are not relevant in this
493:         // context since a collateral check will always be done on non-settlement methods.
494:         (didSettle, /* */) = settleVaultAccount(vaultAccount, vaultConfig);
495: 
496:         // If the account did not settle but is in the prime cash maturity, assess a fee.
497:         if (!didSettle && vaultAccount.maturity == Constants.PRIME_CASH_VAULT_MATURITY) {
498:             // The prime cash fee is deducted from the tempCashBalance
499:             vaultConfig.assessVaultFees(
500:                 vaultAccount,
501:                 vaultConfig.primeRate.convertFromUnderlying(vaultAccount.accountDebtUnderlying).neg(),
502:                 vaultAccount.maturity,
503:                 block.timestamp
504:             );
505:         }
506:     }
```

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultAccount.sol#L508-L520

```solidity
File: VaultAccount.sol
508:     function accruePrimeCashFeesToDebtInLiquidation(
509:         VaultAccount memory vaultAccount,
510:         VaultConfig memory vaultConfig
511:     ) internal returns (VaultState memory) {
512:         vaultConfig.assessVaultFees(
513:             vaultAccount,
514:             vaultConfig.primeRate.convertFromUnderlying(vaultAccount.accountDebtUnderlying).neg(),
515:             vaultAccount.maturity,
516:             block.timestamp
517:         );
518: 
519:         return accruePrimeCashFeesToDebt(vaultAccount, vaultConfig);
520:     }
```

## Impact

Ability to avoid paying vault fees altogether, disincentivising the use of non-prime vaults over prime vaults as sophisticated users can game fee mechanics.

## Code Snippet

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultAccount.sol#L475-L480

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultAccount.sol#L487-L506

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultAccount.sol#L508-L520

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultConfiguration.sol#L277-L303

https://github.com/sherlock-audit/2023-03-notional-0xleastwood/blob/main/contracts-v2/contracts/internal/vaults/VaultConfiguration.sol#L236-L268

## Tool used

Manual Review

## Recommendation

Total debt in all borrowed currencies needs to be taken into consideration when calling `VaultConfiguration.assessVaultFees()`. 

`VaultSecondaryBorrow.getSecondaryBorrowCollateralFactors()` can be queried to retrieve the vault account's total secondary debt denominated in the primary account debt which can then be converted into prime cash alongside `accountDebtUnderlying`.

**Comment by Jiaren-tang** [comment]
Escalate for 10 USDC. based on the sponsor comments the issue is not a medium

> This is true, but it's not a vulnerability. It's also not necessarily a business problem in practice for a few reasons. It is suboptimal though.

and

> True, however, Notional does collect fees on borrows via the fCash curve and Prime Debt fees already. I don't think we will be changing the existing functionality.

**Comment by 0xleastwood** [comment]
> Escalate for 10 USDC. based on the sponsor comments the issue is not a medium
> 
> > This is true, but it's not a vulnerability. It's also not necessarily a business problem in practice for a few reasons. It is suboptimal though.
> 
> and
> 
> > True, however, Notional does collect fees on borrows via the fCash curve and Prime Debt fees already. I don't think we will be changing the existing functionality.

Disagree, you can avoid paying fees altogether in a leveraged vault by restructuring a vault account's underlying debt holdings. By self-liquidating and re-borrowing into a prime vault, we can reduce primary debt to almost zero and denominate an account's debt almost entirely in secondary currencies. As a result, continuous fees charged on prime debt will be zero and this vault account will disproportionately benefit from structuring their vault account in this way. If anything, I think it would be almost fair to upgrade this to `high` because it is a key part of the leveraged vault implementation which is used to generate significant fee revenue for Notional and this can be circumvented.

**Comment by jeffywu** [comment]
In theory this is true, but avoiding fees this way will likely put the account at extremely high risk for liquidation or simply a lot of IL. The secondary borrow currencies exist to reduce IL potential when providing liquidity on a two token pool. Borrowing in both primary and secondary is a beneficial feature, it's not likely that avoiding how the vault is intended to be used for the purposes of avoiding fees will be in any way beneficial to the user.

**Comment by 0xleastwood** [comment]
> In theory this is true, but avoiding fees this way will likely put the account at extremely high risk for liquidation or simply a lot of IL. The secondary borrow currencies exist to reduce IL potential when providing liquidity on a two token pool. Borrowing in both primary and secondary is a beneficial feature, it's not likely that avoiding how the vault is intended to be used for the purposes of avoiding fees will be in any way beneficial to the user.

The idea would be to put yourself at risk so you could deleverage the primary currency on your own leveraged vault. Once this has been done, you re-borrow some amount and repeat the process until most of the debt for your account is in secondary currencies. You would still have claim on ideally the same number of vault shares but would end up ultimately paying less fees than other users. I agree that you would be exposing yourself to potentially increased IL, but it could also be a strategy for users to gain exposure to specific currency(s). Users could still benefit from the vault strategy while having debt denominated in only one currency. Hence, the user would potentially be able to take a position in a strategy which yields them more than comparative strategies, yet only be exposed to price movements in one currency.

**Comment by 0xleastwood** [comment]
I respect the decision of the judge on this one. I understand both sides to the argument but still stand with my comments.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low as this can be considered as the design decision and the possibility of a complex abuse to avoid paying fees while putting their own position at risk, is considered as acceptable risk by the protocol.
