### ISSUE TITLE
PRAISE - The address of `owner`, `pauseRouter_`, `pauseGaurdian_` can't be updated via the initialize() function during future L2 redeployments because the constructor sets `hasInitialized` to true.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#2]
PRAISE

medium

# The address of `owner`, `pauseRouter_`, `pauseGaurdian_` can't be updated via the initialize() function during future L2 redeployments because the constructor sets `hasInitialized` to true.

## Summary
The address of `owner`, `pauseRouter_`, `pauseGaurdian_` can't be updated via the initialize() function because the constructor sets `hasInitialized` flag to true.

## Vulnerability Detail
The constructor sets the `hasInitialized` flag to true as soon as the contract is deployed, which effectively locks the contract in its assumed initialized state. But, the address of `owner`, `pauseRouter_` and  `pauseGuardian_` weren't updated in constructor, the devs want to update them via the initialize() function. 
This won't be possible because the initialize() function checks and requires that `hasInitialized` flag must be false before the function can be called. In Router.sol's case the constructor sets the `hasInitialized` flag to true making it impossible to update `owner`, `pauseRouter_` and `pauseGaurdian_`. This is critical as this contract `Router.sol` won't have these roles set.

i spoke with one of the Devs and he said "the `initialize() function` method is mainly left there for future L2 deployments". But i still insist to submit this because since the constructor sets `hasInitialized` flag to `true`, the initialize() function can't be called due to this require statement
```solidity
        require(msg.sender == DEPLOYER && !hasInitialized);
```  
pls take note of `!hasInitialized` in the above require statement.

Even in future L2 deployments the Devs won't be able to use the initialize() function unless they'll have to redeploy the router.sol and set the `hasInitialized` flag to false in the constructor. 

## Impact
Router.sol won't have `owner`, `pauseRouter_` and `pauseGaurdian_` roles set up during future L2 deployments
Contracts that inherit the Router.sol and try to use these roles will have issues. 
## Code Snippet
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L66-L88

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/Router.sol#L90-L100
## Tool used

Manual Review

## Recommendation
set `hasInitialized` flag to false in the constructor since the contract isn't fully initialized, to make it possible to update `owner`, `pauseRouter_` and `pauseGaurdian_`  via the initialize() function and THEN IMPLEMENT ACCESS CONTROL ON THE `initialize()` function WITH MAYBE AN `ONLYOWNER` MODIFIER OR A REQUIRE STATEMENT.

**Comment by Love4codes** [comment]
Escalate for 10 USDC 

I strongly believe this is an issue. Here is my reason:
1.  router.sol sets the hasInitialized flag to true here in the constructor -- https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/Router.sol#L87

2. The initialize() function has a check to ensure that the hasInitialized flag is false 
```solidity
        require(msg.sender == DEPLOYER && !hasInitialized);
```
you'll see that here --https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/Router.sol#L92

**so the initialize() function won't be callable because the require statement will always revert this is due to the constructor setting the hasInitialized flag to true.**

**Comment by 0xleastwood** [comment]
> https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/Router.sol#L92

`pauseRouter` and `pauseGuardian` can be updated via `GovernanceAction.setPauseRouterAndGuardian()`.

`owner` can be updated via `GovernanceAction.transferOwnership()`. 

No need to re-initialise these values because Notional's governance can handle this as it wishes.

**Comment by Love4codes** [comment]
> > https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/Router.sol#L92
> 
> `pauseRouter` and `pauseGuardian` can be updated via `GovernanceAction.setPauseRouterAndGuardian()`.
> 
> `owner` can be updated via `GovernanceAction.transferOwnership()`.
> 
> No need to re-initialise these values because Notional's governance can handle this as it sees fit.

**"i spoke with one of the Devs and he said "the initialize() function method is mainly left there for future L2 deployments"**
 
please can you confirm from the devs

**Comment by 0xleastwood** [comment]
> > > https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/Router.sol#L92
> > 
> > 
> > `pauseRouter` and `pauseGuardian` can be updated via `GovernanceAction.setPauseRouterAndGuardian()`.
> > `owner` can be updated via `GovernanceAction.transferOwnership()`.
> > No need to re-initialise these values because Notional's governance can handle this as it sees fit.
> 
> **"i spoke with one of the Devs and he said "the initialize() function method is mainly left there for future L2 deployments"**
> 
> please can you confirm from the devs

My best guess is that this is because L2 deployments are considered fresh. So this is needed to setup state on the target L2.

**Comment by Love4codes** [comment]
> > > > https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/Router.sol#L92
> > > 
> > > 
> > > `pauseRouter` and `pauseGuardian` can be updated via `GovernanceAction.setPauseRouterAndGuardian()`.
> > > `owner` can be updated via `GovernanceAction.transferOwnership()`.
> > > No need to re-initialise these values because Notional's governance can handle this as it sees fit.
> > 
> > 
> > **"i spoke with one of the Devs and he said "the initialize() function method is mainly left there for future L2 deployments"**
> > please can you confirm from the devs
> 
> My best guess is that this is because L2 deployments are considered fresh. So this is needed to setup state on the target L2.

yes exactly

**Comment by 0xleastwood** [comment]
Yes, but the `hasInitialized` variable will be set to false on L2 because the state is completely anew. We aren't porting over the state from L1 -> L2. So there is no issue, this will work as a typical deployment. Proxies don't call the constructor the same way you would normally expect, that's the whole point of having the `initialize()` function in the first place.

**Comment by 0xleastwood** [comment]
To add a bit more to this, it is fine to set `immutable` variables in a proxy's constructor because these are in-lined during deployment. They are basically hardcoded into the runtime bytecode which ultimately what we are copying. Now the reason why we need the `initialize()` function is because we cannot delegate call from the proxy contract and execute the constructor so we need this function to act in an equivalent way.

**Comment by 0xleastwood** [comment]
`hasInitialized` is set in the constructor to prevent the implementation contract from having its ownership taken over. There have been vulnerabilities in the past where you could claim ownership of the implementation contract and upgrade it to a contract which subsequently self-destructs, bricking the proxy contract.

**Comment by Love4codes** [comment]
Okay that makes sense

**Comment by Trumpero** [comment]
Agree with sponsor, this issue should be invalid.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Based on Sponsor comment, this is a non-issue
