### ISSUE TITLE
chaduke - getNetCashGroupValue() might return the wrong updated portfolio index where the function has ended.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#58]
chaduke

medium

# getNetCashGroupValue() might return the wrong updated portfolio index where the function has ended.

## Summary
``getNetCashGroupValue()`` might return the wrong updated portfolio index where the function has ended when ``a.assetType != Constants.FCASH_ASSET_TYPE`` and ``a.currencyId != cashGroup.currencyId`` are both true. 

## Vulnerability Detail
``getNetCashGroupValue()`` returns the present value of all assets in the cash group as prime cash and the updated portfolio index where the function has ended.

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/valuation/AssetHandler.sol#L134-L169](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/valuation/AssetHandler.sol#L134-L169)

It iterates through each asset ``a`` in ``assets`` to add the new amount of ``presentValueUnderlying``.  The function will break from the for-loop when ``a.currencyId != cashGroup.currencyId``:

```javascript
if (a.currencyId != cashGroup.currencyId) break;
```
so that the correct ``j`` value, which is the updated portfolio index where the function has ended can be returned. 

Unfortunately, the following statement preceding the above statement might make the function return the wrong index. 

```javascript
if (a.assetType != Constants.FCASH_ASSET_TYPE) continue;
```

The main problem is that, when ``a.assetType != Constants.FCASH_ASSET_TYPE`` and ``a.currencyId != cashGroup.currencyId`` are both true., instead of breaking from the for-loop, the function will continue to the next iteration due to the order of these two statements, as a result, the value of ``j`` will be advanced by 1 and the the wrong ``j`` will be returned. 

For example, suppose when j=2, we have ``a.assetType != Constants.FCASH_ASSET_TYPE`` and ``a.currencyId != cashGroup.currencyId`` are both true, instead of returning ``j=2`` as the index, the function will continue for the next iteration, and then return an index > 2. 

## Impact
``getNetCashGroupValue()`` might return the wrong updated portfolio index where the function has ended when ``a.assetType != Constants.FCASH_ASSET_TYPE`` and ``a.currencyId != cashGroup.currencyId`` are both true. 

## Code Snippet
See above

## Tool used
VSCode

Manual Review

## Recommendation
Change the order of these two statements, then the correct ``j``` will be returned. 

```diff
function getNetCashGroupValue(
        PortfolioAsset[] memory assets,
        CashGroupParameters memory cashGroup,
        uint256 blockTime,
        uint256 portfolioIndex
    ) internal view returns (int256, uint256) {
        int256 presentValueInPrime;
        int256 presentValueUnderlying;

        uint256 j = portfolioIndex;
        for (; j < assets.length; j++) {
            PortfolioAsset memory a = assets[j];
-            if (a.assetType != Constants.FCASH_ASSET_TYPE) continue;
            // If we hit a different currency id then we've accounted for all assets in this currency
            // j will mark the index where we don't have this currency anymore
            if (a.currencyId != cashGroup.currencyId) break;
+            if (a.assetType != Constants.FCASH_ASSET_TYPE) continue;


            uint256 oracleRate = cashGroup.calculateOracleRate(a.maturity, blockTime);

            int256 pv =
                getRiskAdjustedPresentfCashValue(
                    cashGroup,
                    a.notional,
                    a.maturity,
                    blockTime,
                    oracleRate
                );
            presentValueUnderlying = presentValueUnderlying.add(pv);
        }

        presentValueInPrime = presentValueInPrime.add(
            cashGroup.primeRate.convertFromUnderlying(presentValueUnderlying)
        );

        return (presentValueInPrime, j);
    }
```

**Comment by jeffywu** [comment]
Invalid, the loop will break on any change in the fCash currency id. Non fCash assets will be excluded from the calculation (in fact, none are allowed):

Examples:
```
Portfolio:
fCash, currencyId 1
fCash, currencyId 2
fCash, currencyId 3
```
Breaks on currencyid = 2

Portfolio:
```
fCash, currencyId 1
fCash, currencyId 2
LT, currencyId 2
fCash, currencyId 3
```

Breaks on currency id 2 and 3

Portfolio:
```
fCash, currencyId 1
LT, currencyId 2
fCash, currencyId 2
fCash, currencyId 3
```

Still breaks on currency id 2 and 3

Portfolio:
```
fCash, currencyId 1
LT, currencyId 2
fCash, currencyId 3
```

Skips LT at currency id 2 and breaks on currency id 3, this is appropriate.
