### ISSUE TITLE
chaduke - executeLowLevelCall() fails to check msg.value == msgValue and check ``target`` is a valid contract address.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#60]
chaduke

high

# executeLowLevelCall() fails to check msg.value == msgValue and check ``target`` is a valid contract address.

## Summary
``excuteLowLevelCall()`` fails to check ``msg.value == msgValue``. As a result, when ``msg.value > msgValue``, the user will lose ETH to the contract. Otherwise,  ``msg.value < msgValue``, the user will steal ETH from the contract. 

The function also fails to check ``target`` is a valid contract address and as a result, it might have a silent  failure.

## Vulnerability Detail
``excuteLowLevelCall()`` allows a user to invoke a low-level call to an external contract. 

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/protocols/GenericToken.sol#L63-L70](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/balances/protocols/GenericToken.sol#L63-L70)

However, the function fails to check whether  ``msg.value == msgValue``.  As a result, when ``msg.value > msgValue``, the user will lose ETH to the contract. Otherwise,  ``msg.value < msgValue``, the user will steal ETH from the contract. 

The function also fails to check ``target`` is a valid contract address and as a result, it might have a silent  failure.

## Impact
``excuteLowLevelCall()`` fails to check ``msg.value == msgValue``. As a result, when ``msg.value > msgValue``, the user will lose ETH to the contract. Otherwise,  ``msg.value < msgValue``, the user will steal ETH from the contract. 

The function also fails to check ``target`` is a valid contract address and as a result, it might have a silent  failure.

## Tool used
VSCode

Manual Review

## Recommendation
1)Check and make sure ``msg.value == msgValue``:
2) Check and make sure ``target`` is a valid contract address to avoid silent  failure.

```diff
 function executeLowLevelCall(
        address target,
        uint256 msgValue,
        bytes memory callData
    ) internal {

+     if(msgValue != msg.value) revert notEqualMsgValue();
+    if(!isContract(target)) revert notValidTarge(target);

        (bool status, bytes memory returnData) = target.call{value: msgValue}(callData);
        require(status, checkRevertMessage(returnData));
    }


  function isContract(address account) internal view returns (bool) {
        // This method relies on extcodesize/address.code.length, which returns 0
        // for contracts in construction, since the code is only stored at the end
        // of the constructor execution.

        return account.code.length > 0;
    }
```

**Comment by jeffywu** [comment]
Invalid, the contract does not always forward msg.value during execute low level call.
