### ISSUE TITLE
chaduke - getfCashExchangeRate() has a division-before-multiplication rounding error.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#63]
chaduke

high

# getfCashExchangeRate() has a division-before-multiplication rounding error.

## Summary
``getfCashExchangeRate()`` has a division-before-multiplication rounding down error. 

## Vulnerability Detail
``getfCashExchangeRate()`` allows a user to get the ``exchangeRate`` from ``timeToInterest`` and ``timeToMaturity``:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/markets/InterestRateCurve.sol#L499-L510](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/markets/InterestRateCurve.sol#L499-L510)

However, the following line has a division-before-multiplication round down error:

```javascript
int128 expValue =
            ABDKMath64x64.fromUInt(interestRate.mul(timeToMaturity).div(Constants.YEAR));
```

This is because function ``fromUint()`` will shift the input to the left by 64 bits, which is equivalent to a multiplication. However, this is after the division by Constants.YEAR first. As a result, it will introduce up to 31,556,925 rounding down error on the right, and ``expValue`` can be off by 1*0x10000000000000000.

## Impact
``getfCashExchangeRate()`` has a division-before-multiplication round down error, and exp can be off by ``expValue`` can be off by 1*0x10000000000000000, which will affect the final returned result ``exchangeRate`` since the error is introduced in the exponent. 

## Tool used
VScode

Manual Review

## Recommendation
We should perform multiplication first and then division:

```diff
function getfCashExchangeRate(
        uint256 interestRate,
        uint256 timeToMaturity
    ) internal pure returns (int256 exchangeRate) {
-        int128 expValue =ABDKMath64x64.fromUInt(interestRate.mul(timeToMaturity).div(Constants.YEAR));
+       int128 expValue =ABDKMath64x64.fromUInt(interestRate.mul(timeToMaturity)) / Constants.YEAR;

        int128 expValueScaled = ABDKMath64x64.div(expValue, Constants.RATE_PRECISION_64x64);
        int128 expResult = ABDKMath64x64.exp(expValueScaled);
        int128 expResultScaled = ABDKMath64x64.mul(expResult, Constants.RATE_PRECISION_64x64);

        exchangeRate = ABDKMath64x64.toInt(expResultScaled);
    }
```

**Comment by jeffywu** [comment]
I would rank this as low / informational. The rounding errors here are insignificant, they happen at 1e-9 decimal places.
