### ISSUE TITLE
chaduke - struct PrimeCashFactorsStorage reserves only 128 bits, not 128 bytes, and will cause future storage collision/confusion.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#68]
chaduke

high

# struct PrimeCashFactorsStorage reserves only 128 bits, not 128 bytes, and will cause future storage collision/confusion.

## Summary
struct ``PrimeCashFactorsStorage`` reserves only 128 bits, not 128 bytes, and will cause future storage collision/confusion.

## Vulnerability Detail

struct ``PrimeCashFactorsStorage`` is supposed to reserve 128 bytes for the following: 
```javascrsipt
uint128 _reserved;
    // Reserving the next 128 bytes for future use in case we decide to implement debt
    // caps on a currency. In that case, we will need to track the total fcash overall
    // and subtract the total debt held in vaults.
    // uint32 maxUnderlyingDebt;
    // uint32 totalfCashDebtOverall;
    // uint32 totalfCashDebtInVaults;
    // uint32 totalPrimeDebtInVaults;
    // 8 bytes left
    
    // Storage slot 3 [Prime Scalars, 240 bytes]
    // Scalars are stored in 18 decimal precision (i.e. double rate precision) and uint80
    // maxes out at approx 1,210,000e18
    // ln(1,210,000) = rate * years = 14
    // Approx 46 years at 30% interest
    // Approx 233 years at 6% interest
```

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/global/Types.sol#L675-L712](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/global/Types.sol#L675-L712)

Instead, it only reserves 128 bits, not 128 bytes. 

As a result, it will cause future storage collision/confusion in the future and leads to unpredictable behavior of the protocol, including losing funds. 

## Impact
struct PrimeCashFactorsStorage reserves only 128 bits, not 128 bytes, and will cause future storage collision/confusion.

## Tool used
VSCode

Manual Review

## Recommendation

Changes the reservation to 128 bytes from 128 bits.

**Comment by jeffywu** [comment]
Invalid, clearly a typo in the comment.
