### ISSUE TITLE
chaduke - _setPrimeCashFactorsOnAccrue() fails to enforce s.lastTotalUnderlyingValue is under the cap of s.lastTotalUnderlyingValue.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#69]
chaduke

medium

# _setPrimeCashFactorsOnAccrue() fails to enforce s.lastTotalUnderlyingValue is under the cap of s.lastTotalUnderlyingValue.

## Summary
``_setPrimeCashFactorsOnAccrue()`` fails to enforce ``s.lastTotalUnderlyingValue`` is under the cap of ``s.lastTotalUnderlyingValue``. 
Similarly, ``updateTotalPrimeSupply()`` fails to enforce ``s.lastTotalUnderlyingValue`` is under the cap of ``s.lastTotalUnderlyingValue``. As a result, both functions might change  ``s.lastTotalUnderlyingValue`` to a value that exceeds  the cap of ``s.lastTotalUnderlyingValue``. 

## Vulnerability Detail
``_setPrimeCashFactorsOnAccrue()``  allows one to change ``s.lastTotalUnderlyingValue``:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L243-L267](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L243-L267)

 ``updateTotalPrimeSupply()`` also allows one to change ``s.lastTotalUnderlyingValue``:

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L326-L355](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L326-L355)

However, both of them fail to check and enforce ``s.lastTotalUnderlyingValue`` is under the cap of ``s.lastTotalUnderlyingValue``, as a result, when  ``s.lastTotalUnderlyingValue`` is changed, it might exceed the cap specified by ``s.lastTotalUnderlyingValue``.

## Impact
``_setPrimeCashFactorsOnAccrue()`` fails to enforce ``s.lastTotalUnderlyingValue`` is under the cap of ``s.lastTotalUnderlyingValue``. 
Similarly, ``updateTotalPrimeSupply()`` fails to enforce ``s.lastTotalUnderlyingValue`` is under the cap of ``s.lastTotalUnderlyingValue``. As a result, both functions might change  ``s.lastTotalUnderlyingValue`` to a value that exceeds  the cap of ``s.lastTotalUnderlyingValue``. 

## Code Snippet
VScode

## Tool used
VSCode

Manual Review

## Recommendation
Make sure the cap is enforced in both cases.

**Comment by jeffywu** [comment]
Invalid, prime supply caps should not be enforced on interest accrual or the whole system will lock up. Caps are only enforced on new deposits.
