### ISSUE TITLE
chaduke - _updatePrimeCashScalars() uses a compound interest rate model rather than a simple interest rate model.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#71]
chaduke

high

# _updatePrimeCashScalars() uses a compound interest rate model rather than a simple interest rate model.

## Summary
``_updatePrimeCashScalars()`` uses a compound interest rate model rather than a simple interest rate model. Therefore, the charged interest depends on how frequent the function is called. A malicious lender can call this function more frequently to solicit more interests. 

## Vulnerability Detail
``_updatePrimeCashScalars()``  is used to accrues interest to the prime cash supply scalar and debt scalar up to the current block time.

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L535-L596](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L535-L596)

it calls the ``_getScalarIncrease()`` function to calculate the new values of ``debtScalar`` and ``supplyScalar``.

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L473-L528](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/pCash/PrimeCashExchangeRate.sol#L473-L528)

But the protocol uses a compound interest model instead of a simple interest model, as can be seen by the way it calculates the new ``debtScalar`` and ``supplyScalar``, it uses multiplication instead of addition:

```javascript
debtScalarWithFee = prior.debtScalar.mulInScalarPrecision(
            Constants.SCALAR_PRECISION.add(
                // No division underflow
                annualDebtRatePostFee.mul(scaledTimeSinceLastAccrue) / Constants.YEAR
            )
        );

        newSupplyScalar = prior.supplyScalar.mulInScalarPrecision(
            Constants.SCALAR_PRECISION.add(
                // No division underflow
                annualSupplyRate.mul(scaledTimeSinceLastAccrue) / Constants.YEAR
            )
        );
```

This means, if the function is called more frequently, both values can be boosted in a compound way rather than growing linearly. 

In summary, the interest model is a compound model, the accrued interests can be boosted by calling the function more frequently to charge an effective higher interest rate. 

## Impact
``_updatePrimeCashScalars()`` uses a compound interest rate model rather than a simple interest rate model. Therefore, the charged interest depends on how frequent the function is called. A malicious lender can call this function more frequently to solicit more interests. 

## Tool used
VScode

Manual Review

## Recommendation
Use addition rather than multiplication to calculate new ``debtScalar`` and ``supplyScalar`` so that the model will be a simple interest model.

**Comment by jeffywu** [comment]
Invalid, this is the intended design.
