### ISSUE TITLE
chaduke - deleteAsset() does NOT allow the deletion of an asset from portfolioState.newAssets.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#77]
chaduke

medium

# deleteAsset() does NOT allow the deletion of an asset from portfolioState.newAssets.

## Summary
``deleteAsset()`` does NOT allow the deletion of an asset from ``portfolioState.newAssets``. It only allows the user to delete an asset from ``portfolioState.storedAssets``.

## Vulnerability Detail

``deleteAsset()`` allows one to delete an asset from a portfolio. 

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/portfolio/PortfolioHandler.sol#L312-L353](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/portfolio/PortfolioHandler.sol#L312-L353)

However, a portfolio has two arrays for the assets: ``portfolioState.storedAssets``, ``portfolioState.newAssets``. While the function ``addAsset()`` considers both arrays, ``deleteAsset()`` only considers the ``portfolioState.storedAssets`` array.  It is possible that an asset is added to ``portfolioState.newAssets`` and then needs to be deleted later, but ``deleteAsset()`` only supports the deletion of an asset from  ``portfolioState.storedAssets``, not from ``portfolioState.newAssets``.

## Impact
``deleteAsset()`` does NOT allow the deletion of an asset from portfolioState.newAssets.

## Tool used
VScode

Manual Review

## Recommendation
Create a new function so that a user can delete an asset from ``portfolioState.newAssets`` as well.

**Comment by jeffywu** [comment]
Invalid, this is not required. A `newAsset` with a zero balance will not be stored.
