### ISSUE TITLE
chaduke - ``Market#addLiquidity()`` has a divide-by-zero error when market.totalPrimeCash = 0.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#88]
chaduke

medium

# ``Market#addLiquidity()`` has a divide-by-zero error when market.totalPrimeCash = 0.

## Summary
``Market#addLiquidity()`` has a divide-by-zero error when ``market.totalPrimeCash = 0``.

## Vulnerability Detail
``addLiquidity()`` allows a user to add liquidity to a market, assuming that it is initialized.

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/markets/Market.sol#L27-L45](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/markets/Market.sol#L27-L45)

However, the following statements have a divide-by-error error when market.totalPrimeCash = 0.

```javascript
 liquidityTokens = market.totalLiquidity.mul(primeCash).div(market.totalPrimeCash);
        // No need to convert this to underlying, primeCash / totalPrimeCash is a unitless proportion.
        fCash = market.totalfCash.mul(primeCash).div(market.totalPrimeCash);
```

## Impact
``Market#addLiquidity()`` has a divide-by-zero error when ``market.totalPrimeCash = 0``.

## Tool used
VScode

Manual Review

## Recommendation
Deal with the case of market.totalPrimeCash = 0 so that divide-by-error will not occur.

**Comment by jeffywu** [comment]
True, however, in practice totalPrimeCash does not equal zero due to how markets are initialized. Would consider any handling here to be redundant.
