### ISSUE TITLE
chaduke - SettleBitmapAssets#settleBitmappedCashGroup() will fail to settle assets when newSettleTime is not on an exact bit.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#89]
chaduke

medium

# SettleBitmapAssets#settleBitmappedCashGroup() will fail to settle assets when newSettleTime is not on an exact bit.

## Summary
``SettleBitmapAssets#settleBitmappedCashGroup()`` will fail to settle assets when ``newSettleTime`` is not on an exact bit.

## Vulnerability Detail

``SettleBitmapAssets#settleBitmappedCashGroup()`` will settle all assets
 that have matured and remap the bitmap to correspond to the current time.

[https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/settlement/SettleBitmapAssets.sol#L30-L84](https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/internal/settlement/SettleBitmapAssets.sol#L30-L84)

at L47, it says "Do not need to worry about validity, if newSettleTime is not on an exact bit we will settle up until  the closest maturity that is less than newSettleTime."

L49 implements this by ignoring the ``isValid`` flag. 

```javascript
 (uint256 lastSettleBit, /* isValid */) = DateTime.getBitNumFromMaturity(oldSettleTime, newSettleTime);
```

However, at L74, for those assets that have not yet matured, it requires the ``isValid`` is true:

```javascript
            (uint256 newBitNum, bool isValid) = DateTime.getBitNumFromMaturity(newSettleTime, maturity);
            require(isValid); // dev: invalid new bit num
```  
This means, when ``newSettleTime`` is not on an exact bit for the remaining assets, the function will revert and as a result, none of the previous assets can be settled either. 

## Impact
``SettleBitmapAssets#settleBitmappedCashGroup()`` will fail to settle assets when ``newSettleTime`` is not on an exact bit.

## Tool used
VScode

Manual Review

## Recommendation
Ignore the ``isValid`` as well for the calculation of the new bitmap.

**Comment by jeffywu** [comment]
Invalid, this misunderstands how the code works. The newSettleTime may be any arbitrary date which which sets the position of the `lastSettleBit`, the second call asserts that the `newBitNum` exactly corresponds to the maturity.
