### ISSUE TITLE
ShadowForce - getVaultAccountWithFeeAccrual not exposed to the router contract

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#90]
ShadowForce

medium

# getVaultAccountWithFeeAccrual not exposed to the router contract

## Summary
getVaultAccountWithFeeAccrual not exposed to the router contract
## Vulnerability Detail
```solidity
    function getVaultAccountWithFeeAccrual(address account, address vault) external override view returns (
        VaultAccount memory vaultAccount,
        int256 accruedPrimeVaultFeeInUnderlying
    )
```
In the contract VaultAccountHealth.sol there is a function `getVaultAccountWithFeeAccrual` which is not exposed to the router contract. As we know router contract directs a users calls and delegates them to another contract for use in the protocol. Because the function `getVaultAccountWithFeeAccrual` is not exposed to the router contract, it may cause problems.
## Impact
no one can read the accruedPrimeVaultFeeInUnderlying state, the Notional Website UI is impacted and users do not know the accured prime vault fee, the external protocol that integrates with notional also have a difficult time finding accured prime vault fee. This can mislead protocols and users to go into positions with incorrect information and state of the protocol.
## Code Snippet
https://github.com/notional-finance/contracts-v2/blob/b20a45c912785fab5f2b62992e5260f44dbae197/contracts/external/actions/VaultAccountHealth.sol#L105-L131
## Tool used

Manual Review

## Recommendation
we recommend to expose the `getVaultWithFeeAccrual` function in the router contract

**Comment by JeffCX** [comment]
Escalate for 10 USDC. this should be a valid medium 

https://docs.sherlock.xyz/audits/judging/judging

> Incorrect values in View functions are by default considered low. 
Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.

in this case, the protocol failed to expose the getVaultAccountWithFeeAccrual function via router

both the frontend and the external protocol cannot read the accruedPrimeVaultFeeInUnderlying state because they cannot call getVaultAccountWithFeeAccrual via the router contract, lends to integration issue

```solidity
    function getVaultAccountWithFeeAccrual(address account, address vault) external override view returns (
        VaultAccount memory vaultAccount,
        int256 accruedPrimeVaultFeeInUnderlying
    ) {
        VaultConfig memory vaultConfig = VaultConfiguration.getVaultConfigView(vault);
        vaultAccount = VaultAccountLib.getVaultAccount(account, vaultConfig);

        if (vaultAccount.maturity == Constants.PRIME_CASH_VAULT_MATURITY) {
            // Save this because it is re-written inside the calculate vault fees method
            uint256 lastUpdateBlockTime = vaultAccount.lastUpdateBlockTime;
            accruedPrimeVaultFeeInUnderlying = vaultConfig.primeRate.convertToUnderlying(
                vaultConfig.calculateVaultFees(
                    vaultAccount,
                    vaultConfig.primeRate.convertFromUnderlying(vaultAccount.accountDebtUnderlying).neg(),
                    vaultAccount.maturity,
                    block.timestamp
                )
            );

            // Reset the last update block time and add the accrued vault fee to the total debt (use
            // subtraction since debts are negative).
            vaultAccount.lastUpdateBlockTime = lastUpdateBlockTime;
            vaultAccount.accountDebtUnderlying = vaultAccount.accountDebtUnderlying.sub(
                accruedPrimeVaultFeeInUnderlying
            );
        }
    }
```

**Comment by 0xleastwood** [comment]
> getVaultAccountWithFeeAccrual

This function is not provably used in a larger function which would result in a loss of funds. The same reason we can't assume an issue is valid for EIP compliance with no integrations, we can't apply the same thinking to this.

**Comment by 0xleastwood** [comment]
> Escalate for 10 USDC. this should be a valid medium
> 
> https://docs.sherlock.xyz/audits/judging/judging
> 
> > Incorrect values in View functions are by default considered low.
> > Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.
> 
> in this case, the protocol failed to expose the getVaultAccountWithFeeAccrual function via router
> 
> both the frontend and the external protocol cannot read the accruedPrimeVaultFeeInUnderlying state because they cannot call getVaultAccountWithFeeAccrual via the router contract, lends to integration issue
> 
> ```solidity
>     function getVaultAccountWithFeeAccrual(address account, address vault) external override view returns (
>         VaultAccount memory vaultAccount,
>         int256 accruedPrimeVaultFeeInUnderlying
>     ) {
>         VaultConfig memory vaultConfig = VaultConfiguration.getVaultConfigView(vault);
>         vaultAccount = VaultAccountLib.getVaultAccount(account, vaultConfig);
> 
>         if (vaultAccount.maturity == Constants.PRIME_CASH_VAULT_MATURITY) {
>             // Save this because it is re-written inside the calculate vault fees method
>             uint256 lastUpdateBlockTime = vaultAccount.lastUpdateBlockTime;
>             accruedPrimeVaultFeeInUnderlying = vaultConfig.primeRate.convertToUnderlying(
>                 vaultConfig.calculateVaultFees(
>                     vaultAccount,
>                     vaultConfig.primeRate.convertFromUnderlying(vaultAccount.accountDebtUnderlying).neg(),
>                     vaultAccount.maturity,
>                     block.timestamp
>                 )
>             );
> 
>             // Reset the last update block time and add the accrued vault fee to the total debt (use
>             // subtraction since debts are negative).
>             vaultAccount.lastUpdateBlockTime = lastUpdateBlockTime;
>             vaultAccount.accountDebtUnderlying = vaultAccount.accountDebtUnderlying.sub(
>                 accruedPrimeVaultFeeInUnderlying
>             );
>         }
>     }
> ```

This function is not provably used in a larger function which would result in a loss of funds. The same reason we can't assume an issue is valid for EIP compliance with no integrations, we can't apply the same thinking to this.

**Comment by Trumpero** [comment]
I believe this issue should be a low/info since it doesn't result in any loss of funds.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This issue is a low impact, as pointed out by Lead Watson and Judge.
