### ISSUE TITLE
ShadowForce - ETH locked during migration

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#92]
ShadowForce

high

# ETH locked during migration

## Summary
Migration will lock all ether in the contract
## Vulnerability Detail
The `_initializePrimeCash` function does not handle eth balance retrieval correctly
```solidity
    function _initializePrimeCash(
        uint16 currencyId,
        Token memory assetToken,
        Token memory underlyingToken,
        MigrationSettings memory settings
    ) private {
        // Will set the initial token balance storage to whatever is on the contract at the time
        // of migration.
        PrimeCashExchangeRate.initTokenBalanceStorage(currencyId, settings.primeCashOracle);

        // Any dust underlying token balances will be donated to the prime supply and aggregated into
        // the underlying scalar value. There is currently some dust ETH balance on Notional that will
        // get donated to all prime cash holders.
        uint88 currentAssetTokenBalance = assetToken.convertToInternal(
            IERC20(assetToken.tokenAddress).balanceOf(address(this)).toInt()
        ).toUint().toUint88();
```
As we can see in the snippet above, when the function goes to check balance of ETH inside the contract, it does so with
```solidity
IERC20(assetToken.tokenAddress).balanceOf(address(this)
```
this will not work for native ETH. To correctly retrieve balance of ETH , the contract should call with
```solidity
 address(this).balance
```
because the function does not correctly retrieve the balance of ETH, all of the ETH will be stuck inside the contract inside migration.
## Impact
When migrating, all ETH will be locked inside the contract
## Code Snippet
https://github.com/notional-finance/contracts-v2/blob/b20a45c912785fab5f2b62992e5260f44dbae197/contracts/external/patchfix/MigratePrimeCash.sol#L219-L274
## Tool used

Manual Review

## Recommendation
We recommend the function retrieves the balance of ether inside the contract using
```solidity
address(this).balance
```

**Comment by JeffCX** [comment]
Escalate for 10 USDC. this should be a valid issue,

 as the comment states, the dust ETH should be donated instead of lost in the contract
 
 ```solidity
function _initializePrimeCash(
	uint16 currencyId,
	Token memory assetToken,
	Token memory underlyingToken,
	MigrationSettings memory settings
) private {
	// Will set the initial token balance storage to whatever is on the contract at the time
	// of migration.
	PrimeCashExchangeRate.initTokenBalanceStorage(currencyId, settings.primeCashOracle);

	// Any dust underlying token balances will be donated to the prime supply and aggregated into
	// the underlying scalar value. There is currently some dust ETH balance on Notional that will
	// get donated to all prime cash holders.
	uint88 currentAssetTokenBalance = assetToken.convertToInternal(
		IERC20(assetToken.tokenAddress).balanceOf(address(this)).toInt()
	).toUint().toUint88();
```

**Comment by 0xleastwood** [comment]
> https://github.com/notional-finance/contracts-v2/blob/b20a45c912785fab5f2b62992e5260f44dbae197/contracts/external/patchfix/MigratePrimeCash.sol#L219-L274

So this contract actually uses `TokenHandler for Token` which has an interesting way to handle ETH balances. `TokenHandler.balanceOf()` will check if the token type is native ETH and return `account.balance` if this is true. See the following snippet of code for what this looks like.

```solidity
function balanceOf(Token memory token, address account) internal view returns (uint256) {
    if (token.tokenType == TokenType.Ether) {
        return account.balance;
    } else {
        return IERC20(token.tokenAddress).balanceOf(account);
    }
}
```

**Comment by Trumpero** [comment]
assetToken can't be ETH since it's the depecrated asset token which is cToken.

**Comment by jeffywu** [comment]
Trumpero is correct.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Considering this a non-issue based on the above comments.
